# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-31 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('message', models.TextField(null=True)),
                ('created_time', models.DateTimeField()),
                ('like_count', models.IntegerField()),
                ('love', models.IntegerField()),
                ('wow', models.IntegerField()),
                ('haha', models.IntegerField()),
                ('sad', models.IntegerField()),
                ('angry', models.IntegerField()),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookNewPage',
            fields=[
                ('url', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookNewPost',
            fields=[
                ('url', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('message', models.TextField(null=True)),
                ('picture', models.URLField(null=True)),
                ('link', models.URLField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField()),
                ('shares', models.IntegerField(null=True)),
                ('likes', models.IntegerField()),
                ('love', models.IntegerField()),
                ('wow', models.IntegerField()),
                ('haha', models.IntegerField()),
                ('sad', models.IntegerField()),
                ('angry', models.IntegerField()),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.FacebookNewPage')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.Person')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.Person'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.FacebookNewPost'),
        ),
    ]
