# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooknewpage',
            name='pages_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='facebooknewpost',
            name='posts_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
