# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_message', models.TextField()),
                ('_picture', models.URLField()),
                ('_link', models.URLField()),
                ('_name', models.CharField(max_length=100)),
                ('_description', models.TextField()),
                ('_type', models.CharField(max_length=100)),
                ('_created_time', models.DateTimeField()),
                ('_shares', models.IntegerField()),
                ('_likes', models.IntegerField()),
                ('_loves', models.IntegerField()),
                ('_wows', models.IntegerField()),
                ('_hahas', models.IntegerField()),
                ('_sads', models.IntegerField()),
                ('_angrys', models.IntegerField()),
                ('_post_id', models.CharField(max_length=256)),
                ('_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.Person')),
            ],
        ),
    ]
