# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_person_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_angrys',
            new_name='angrys',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_created_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_hahas',
            new_name='hahas',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_loves',
            new_name='loves',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_sads',
            new_name='sads',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_shares',
            new_name='shares',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_wows',
            new_name='wows',
        ),
        migrations.RemoveField(
            model_name='person',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_post_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='asd', max_length=256, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
