# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20180122_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooknewpage',
            name='since_id',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='facebooknewpost',
            name='since_id',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
