# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20180122_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, choices=[('1', 'Page'), ('2', 'Post')], default='', max_length=60, verbose_name='search')),
            ],
        ),
    ]
