# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_auto_20180111_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='angrys',
            new_name='angry',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='hahas',
            new_name='haha',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='loves',
            new_name='love',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sads',
            new_name='sad',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='wows',
            new_name='wow',
        ),
    ]
