# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
