# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_auto_20180111_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
