# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_auto_20180111_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shares',
            field=models.IntegerField(null=True),
        ),
    ]
